version: '3.1'
services:
  web:
    image: nginx:1.19.2-alpine
    container_name: crm-web
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    restart: unless-stopped
    depends_on:
      - app
      - db
    ports:
      - 8880:80
  app:
    build: docker/app
    container_name: crm-app
    restart: unless-stopped
    volumes:
        - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ./app:/app
  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: crm-db
    volumes:
      - ./db:/Documents
    environment:
      SA_PASSWORD: "Supa!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
        - 1433:1433